---
- name: Copy the kubeadm join script to the worker
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/join-command.sh"
    dest: /tmp/join-command.sh
    mode: '0700'

- name: Join the cluster with kubeadm
  ansible.builtin.command: bash /tmp/join-command.sh
  args:
    creates: /etc/kubernetes/kubelet.conf
