apiVersion: core.loom.io/v1alpha1
kind: NetworkFunction
metadata:
  name: pkt-logger
  namespace: default
  labels:
    nf: logger
spec:
  p4File: "https://raw.githubusercontent.com/mantra6g/iml/refs/heads/main/examples/simple/logger.p4"
  targetSelector:
    p4target.loom.io/arch: v1model