apiVersion: infra.loom.io/v1alpha1
kind: BMv2Target
metadata:
  name: bmv2-target
spec:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"